import type { Organization, SuccessionPlan, Translations, Language, User, SuccessionJourneyStage, ReflectionLog, ValueMirrorData, InstitutionType, Survey, JourneyMilestone } from './types';

export type JourneyTexts = Record<Language, SuccessionJourneyStage[]>;

export const journeyConfig: Record<InstitutionType, JourneyTexts> = {
    corporate: {
        en: [
            { code:"STG1", name:"Assessment & Planning", type: 'planning', duration_mode: "dynamic", base_duration_days: 30, cri: 65, aei: 30, default_tasks: ["Analyze current leadership structure", "Identify future position needs", "Establish selection criteria"] },
            { code:"STG2", name:"Building & Development", type: 'development', duration_mode: "dynamic", base_duration_days: 90, cri: 45, aei: 55, default_tasks: ["Implement qualification programs", "Mentoring and guidance", "Monitor candidate progress"] },
            { code:"STG3", name:"Application & Evaluation", type: 'evaluation', duration_mode: "dynamic", base_duration_days: 90, cri: 25, aei: 75, default_tasks: ["Gradual implementation of transition plans", "Evaluate training effectiveness", "Improve adopted mechanisms"] },
            { code:"STG4", name:"Sustainability & Improvement", type: 'sustainability', duration_mode: "dynamic", base_duration_days: 60, cri: 15, aei: 85, default_tasks: ["Post-transition follow-up", "Monitor impact", "Continuous development"] }
        ],
        ar: [
            { code:"STG1", name:"التقييم والتخطيط", type: 'planning', duration_mode: "dynamic", base_duration_days: 30, cri: 65, aei: 30, default_tasks: ["دراسة الهيكل القيادي الحالي", "تحديد الاحتياجات المستقبلية للمناصب", "وضع معايير الاختيار"] },
            { code:"STG2", name:"البناء والتطوير", type: 'development', duration_mode: "dynamic", base_duration_days: 90, cri: 45, aei: 55, default_tasks: ["تنفيذ برامج التأهيل", "التوجيه والإرشاد", "متابعة تقدم المرشحين"] },
            { code:"STG3", name:"التطبيق والتقويم", type: 'evaluation', duration_mode: "dynamic", base_duration_days: 90, cri: 25, aei: 75, default_tasks: ["التطبيق التدريجي لخطط الانتقال", "تقييم فعالية التدريب", "تحسين الآليات"] },
            { code:"STG4", name:"الاستدامة والتحسين", type: 'sustainability', duration_mode: "dynamic", base_duration_days: 60, cri: 15, aei: 85, default_tasks: ["المتابعة بعد الانتقال", "رصد الأثر", "التطوير المستمر"] }
        ]
    },
    government: {
        en: [
            { code:"STG1", name:"Needs Analysis & Mandate Alignment", type: 'planning', duration_mode: "dynamic", base_duration_days: 45, cri: 75, aei: 25, default_tasks: ["Analyze current leadership structure", "Identify future position needs", "Establish selection criteria"] },
            { code:"STG2", name:"Competency Building & Policy Training", type: 'development', duration_mode: "dynamic", base_duration_days: 120, cri: 50, aei: 50, default_tasks: ["Implement qualification programs", "Mentoring and guidance", "Monitor candidate progress"] },
            { code:"STG3", name:"Service Delivery Simulation & Review", type: 'evaluation', duration_mode: "dynamic", base_duration_days: 90, cri: 30, aei: 70, default_tasks: ["Gradual implementation of transition plans", "Evaluate training effectiveness", "Improve adopted mechanisms"] },
            { code:"STG4", name:"Public Trust & Continuity", type: 'sustainability', duration_mode: "dynamic", base_duration_days: 60, cri: 10, aei: 90, default_tasks: ["Post-transition follow-up", "Monitor impact", "Continuous development"] }
        ],
        ar: [
            { code:"STG1", name:"تحليل الاحتياجات ومواءمة التفويض", type: 'planning', duration_mode: "dynamic", base_duration_days: 45, cri: 75, aei: 25, default_tasks: ["دراسة الهيكل القيادي الحالي", "تحديد الاحتياجات المستقبلية", "وضع معايير الاختيار"] },
            { code:"STG2", name:"بناء الكفاءات والتدريب على السياسات", type: 'development', duration_mode: "dynamic", base_duration_days: 120, cri: 50, aei: 50, default_tasks: ["تنفيذ برامج التأهيل", "التوجيه والإرشاد", "متابعة تقدم المرشحين"] },
            { code:"STG3", name:"محاكاة تقديم الخدمة والمراجعة", type: 'evaluation', duration_mode: "dynamic", base_duration_days: 90, cri: 30, aei: 70, default_tasks: ["التطبيق التدريجي لخطط الانتقال", "تقييم فعالية التدريب", "تحسين الآليات"] },
            { code:"STG4", name:"ثقة الجمهور والاستمرارية", type: 'sustainability', duration_mode: "dynamic", base_duration_days: 60, cri: 10, aei: 90, default_tasks: ["المتابعة بعد الانتقال", "رصد الأثر", "التطوير المستمر"] }
        ]
    },
    education: {
        en: [
            { code:"STG1", name:"Curriculum Review & Vision Setting", type: 'planning', duration_mode: "dynamic", base_duration_days: 45, cri: 60, aei: 40, default_tasks: ["Analyze current leadership structure", "Identify future position needs", "Establish selection criteria"] },
            { code:"STG2", name:"Pedagogical Leadership Development", type: 'development', duration_mode: "dynamic", base_duration_days: 100, cri: 40, aei: 60, default_tasks: ["Implement qualification programs", "Mentoring and guidance", "Monitor candidate progress"] },
            { code:"STG3", name:"Academic Program Implementation", type: 'evaluation', duration_mode: "dynamic", base_duration_days: 100, cri: 20, aei: 80, default_tasks: ["Gradual implementation of transition plans", "Evaluate training effectiveness", "Improve adopted mechanisms"] },
            { code:"STG4", name:"Scholarly Excellence & Succession", type: 'sustainability', duration_mode: "dynamic", base_duration_days: 60, cri: 10, aei: 90, default_tasks: ["Post-transition follow-up", "Monitor impact", "Continuous development"] }
        ],
        ar: [
            { code:"STG1", name:"مراجعة المناهج ووضع الرؤية", type: 'planning', duration_mode: "dynamic", base_duration_days: 45, cri: 60, aei: 40, default_tasks: ["دراسة الهيكل القيادي الحالي", "تحديد الاحتياجات المستقبلية", "وضع معايير الاختيار"] },
            { code:"STG2", name:"تطوير القيادة التربوية", type: 'development', duration_mode: "dynamic", base_duration_days: 100, cri: 40, aei: 60, default_tasks: ["تنفيذ برامج التأهيل", "التوجيه والإرشاد", "متابعة تقدم المرشحين"] },
            { code:"STG3", name:"تنفيذ البرامج الأكاديمية", type: 'evaluation', duration_mode: "dynamic", base_duration_days: 100, cri: 20, aei: 80, default_tasks: ["التطبيق التدريجي لخطط الانتقال", "تقييم فعالية التدريب", "تحسين الآليات"] },
            { code:"STG4", name:"التميز العلمي والتعاقب", type: 'sustainability', duration_mode: "dynamic", base_duration_days: 60, cri: 10, aei: 90, default_tasks: ["المتابعة بعد الانتقال", "رصد الأثر", "التطوير المستمر"] }
        ]
    },
    charity: {
        en: [
            { code:"STG1", name:"Mission Alignment & Stakeholder Analysis", type: 'planning', duration_mode: "dynamic", base_duration_days: 30, cri: 55, aei: 45, default_tasks: ["Analyze current leadership structure", "Identify future position needs", "Establish selection criteria"] },
            { code:"STG2", name:"Fundraising & Community Engagement", type: 'development', duration_mode: "dynamic", base_duration_days: 80, cri: 35, aei: 65, default_tasks: ["Implement qualification programs", "Mentoring and guidance", "Monitor candidate progress"] },
            { code:"STG3", name:"Program Impact Assessment", type: 'evaluation', duration_mode: "dynamic", base_duration_days: 80, cri: 20, aei: 80, default_tasks: ["Gradual implementation of transition plans", "Evaluate training effectiveness", "Improve adopted mechanisms"] },
            { code:"STG4", name:"Legacy & Volunteer Leadership", type: 'sustainability', duration_mode: "dynamic", base_duration_days: 50, cri: 15, aei: 85, default_tasks: ["Post-transition follow-up", "Monitor impact", "Continuous development"] }
        ],
        ar: [
            { code:"STG1", name:"التقييم والتخطيط", type: 'planning', duration_mode: "dynamic", base_duration_days: 30, cri: 55, aei: 45, default_tasks: ["دراسة الهيكل القيادي الحالي", "تحديد الاحتياجات المستقبلية للمناصب", "وضع معايير الاختيار"] },
            { code:"STG2", name:"البناء والتطوير", type: 'development', duration_mode: "dynamic", base_duration_days: 80, cri: 35, aei: 65, default_tasks: ["تنفيذ برامج التأهيل", "التوجيه والإرشاد", "متابعة تقدم المرشحين"] },
            { code:"STG3", name:"التطبيق والتقويم", type: 'evaluation', duration_mode: "dynamic", base_duration_days: 80, cri: 20, aei: 80, default_tasks: ["التطبيق التدريبي لخطط الانتقال", "تقييم فعالية التدريب", "تحسين الآليات"] },
            { code:"STG4", name:"الاستدامة والتحسين", type: 'sustainability', duration_mode: "dynamic", base_duration_days: 50, cri: 15, aei: 85, default_tasks: ["المتابعة بعد الانتقال", "رصد الأثر", "التطوير المستمر"] }
        ]
    }
};

export const improvementAreas: { key: string, name_en: string, name_ar: string }[] = [
    { key: 'strategic_thinking', name_en: 'Strategic Thinking', name_ar: 'التفكير الاستراتيجي' },
    { key: 'team_leadership', name_en: 'Team Leadership', name_ar: 'قيادة الفريق' },
    { key: 'communication', name_en: 'Communication Skills', name_ar: 'مهارات التواصل' },
    { key: 'financial_acumen', name_en: 'Financial Acumen', name_ar: 'الفطنة المالية' },
    { key: 'decision_making', name_en: 'Decision Making', name_ar: 'اتخاذ القرار' },
    { key: 'change_management', name_en: 'Change Management', name_ar: 'إدارة التغيير' },
    { key: 'innovation', name_en: 'Innovation & Creativity', name_ar: 'الابتكار والإبداع' },
];

type ValueMirrorMessages = {
  [key: string]: {
    en: ValueMirrorData;
    ar: ValueMirrorData;
  };
};

export const valueMirrorMessages: ValueMirrorMessages = {
  PROACTIVE_MOMENTUM: {
    en: { emoji: '🚀', quote: 'Momentum is building this week!', feedback: 'Your increased activity and positive reflections are driving great progress.' },
    ar: { emoji: '🚀', quote: 'الزخم يتزايد هذا الأسبوع!', feedback: 'نشاطك المتزايد وتأملاتك الإيجابية تدفع تقدمًا كبيرًا.' }
  },
  COLLABORATION_GROWTH: {
    en: { emoji: '🌿', quote: 'A spirit of collaboration is growing.', feedback: 'Recent logs highlight strong teamwork and mutual support.' },
    ar: { emoji: '🌿', quote: 'روح التعاون تنمو.', feedback: 'السجلات الأخيرة تبرز العمل الجماعي القوي والدعم المتبادل.' }
  },
  LEARNING_AGILITY_UP: {
    en: { emoji: '💡', quote: 'Curiosity is leading to new insights.', feedback: 'Your reflections show a strong commitment to learning and development.' },
    ar: { emoji: '💡', quote: 'الفضول يؤدي إلى رؤى جديدة.', feedback: 'تظهر تأملاتك التزامًا قويًا بالتعلم والتطور.' }
  },
  NEGATIVE_TREND: {
    en: { emoji: '🔧', quote: 'Time to recalibrate and refocus.', feedback: 'Progress has slowed. Let\'s review the current goals and find a new path forward.' },
    ar: { emoji: '🔧', quote: 'حان الوقت لإعادة التقييم والتركيز.', feedback: 'تباطأ التقدم. لنراجع الأهداف الحالية ونجد مسارًا جديدًا للمضي قدمًا.' }
  },
  DEFAULT_ENCOURAGEMENT: {
    en: { emoji: '🌱', quote: 'Every step forward is progress.', feedback: 'Consistency is key. Keep engaging with your development journey.' },
    ar: { emoji: '🌱', quote: 'كل خطوة للأمام هي تقدم.', feedback: 'الاستمرارية هي المفتاح. استمر في التفاعل مع رحلة تطورك.' }
  },
};

export const valueKeywords = {
  en: {
    collaboration: { emoji: '🤝', keywords: ['team', 'collaboration', 'together', 'support', 'co-'] },
    learning: { emoji: '💡', keywords: ['learn', 'develop', 'insight', 'skill', 'understanding'] },
    initiative: { emoji: '🚀', keywords: ['lead', 'initiative', 'proactive', 'drive', 'driven'] },
    resilience: { emoji: '💪', keywords: ['challenge', 'overcome', 'resilient', 'persist', 'tough'] },
    // Fix: Added keywords for behavioral indicators to resolve errors in behaviorTracker service.
    honesty: { emoji: '⚖️', keywords: ['honest', 'integrity', 'truth', 'transparent', 'ethical'] },
    respect: { emoji: '🙌', keywords: ['respect', 'inclusive', 'listen', 'value', 'dignity'] },
    innovation: { emoji: '✨', keywords: ['innovate', 'creative', 'new idea', 'improve', 'invent'] },
    responsibility: { emoji: '🎯', keywords: ['responsible', 'accountable', 'own', 'commit', 'deliver'] },
  },
  ar: {
    collaboration: { emoji: '🤝', keywords: ['فريق', 'تعاون', 'معا', 'دعم', 'مشترك'] },
    learning: { emoji: '💡', keywords: ['تعلم', 'تطور', 'رؤية', 'مهارة', 'فهم'] },
    initiative: { emoji: '🚀', keywords: ['قيادة', 'مبادرة', 'استباقي', 'دفع', 'سعى'] },
    resilience: { emoji: '💪', keywords: ['تحدي', 'تغلب', 'مرونة', 'مثابرة', 'صعب'] },
    // Fix: Added keywords for behavioral indicators to resolve errors in behaviorTracker service.
    honesty: { emoji: '⚖️', keywords: ['صدق', 'نزاهة', 'حقيقة', 'شفافية', 'أخلاقي'] },
    respect: { emoji: '🙌', keywords: ['احترام', 'شامل', 'استماع', 'قيمة', 'كرامة'] },
    innovation: { emoji: '✨', keywords: ['ابتكار', 'إبداع', 'فكرة جديدة', 'تحسين', 'اختراع'] },
    responsibility: { emoji: '🎯', keywords: ['مسؤولية', 'مساءلة', 'ملكية', 'التزام', 'إنجاز'] },
  }
};

export const surveyQuestions_Leadership_Building_Survey_25Q_v1: Survey['sections'] = [
  {
    title: "الانطباع العام",
    questions: [
      { id: "q1", text: "ما هو انطباعك العام عن مرحلة 'البناء والتطوير' حتى الآن؟", type: "text" },
      { id: "q2", text: "إلى أي مدى تشعر أن هذه المرحلة تساهم بشكل مباشر في تطوير جاهزيتك القيادية؟", type: "rating" },
      { id: "q3", text: "ما هي أبرز الإيجابيات التي لمستها في هذه المرحلة؟", type: "text" },
      { id: "q4", text: "ما هي أبرز التحديات أو السلبيات التي واجهتها؟", type: "text" },
    ]
  },
  {
    title: "جودة برامج التأهيل",
    questions: [
      { id: "q5", text: "تقييمك لجودة المحتوى التدريبي المقدم في برامج التأهيل.", type: "rating" },
      { id: "q6", text: "مدى ملاءمة البرامج التدريبية لاحتياجاتك التطويرية المحددة.", type: "rating" },
      { id: "q7", text: "كفاءة المدربين أو الخبراء الذين قدموا البرامج التدريبية.", type: "rating" },
      { id: "q8", text: "هل هناك مواضيع أو مهارات إضافية تقترح إدراجها في برامج التأهيل؟", type: "text" },
    ]
  },
  {
    title: "التوجيه والإرشاد",
    questions: [
      { id: "q9", text: "تقييمك لفعالية جلسات التوجيه والإرشاد (Mentoring).", type: "rating" },
      { id: "q10", text: "مدى التزام وتوافر الموجه (Mentor) لتقديم الدعم المطلوب.", type: "rating" },
      { id: "q11", text: "إلى أي مدى ساهم الموجه في مساعدتك على التغلب على التحديات المهنية؟", type: "rating" },
      { id: "q12", text: "هل لديك أي مقترحات لتحسين آلية التوجيه والإرشاد؟", type: "text" },
    ]
  },
  {
    title: "الجاهزية القيادية",
    questions: [
      { id: "q13", text: "بعد المشاركة في هذه المرحلة، ما هو تقييمك لمدى تطور مهاراتك في التفكير الاستراتيجي؟", type: "rating" },
      { id: "q14", text: "تقييمك لمدى تطور قدرتك على قيادة وتحفيز فريق العمل.", type: "rating" },
      { id: "q15", text: "تقييمك لمدى تطور مهاراتك في اتخاذ القرارات بناءً على البيانات.", type: "rating" },
      { id: "q16", text: "تقييمك لمدى تطور قدرتك على إدارة التغيير والتعامل مع المواقف الصعبة.", type: "rating" },
      { id: "q17", text: "هل تشعر بثقة أكبر في قدرتك على تولي مسؤوليات الدور القيادي المستهدف؟", type: "rating" },
    ]
  },
  {
    title: "الأثر والتطبيق",
    questions: [
      { id: "q18", text: "إلى أي مدى تمكنت من تطبيق ما تعلمته في مهام عملك اليومية؟", type: "rating" },
      { id: "q19", text: "هل لمست أثراً إيجابياً على أدائك أو أداء فريقك نتيجة لتطبيق المهارات المكتسبة؟", type: "rating" },
      { id: "q20", text: "اذكر مثالاً محدداً لموقف تمكنت فيه من تطبيق مفهوم أو مهارة جديدة بنجاح.", type: "text" },
      { id: "q21", text: "ما هي العوائق (إن وجدت) التي تحد من قدرتك على تطبيق ما تعلمته؟", type: "text" },
    ]
  },
  {
    title: "التوصيات والتطوير",
    questions: [
      { id: "q22", text: "بناءً على تجربتك، ما هي أهم توصياتك لتحسين هذه المرحلة للمرشحين في المستقبل؟", type: "text" },
      { id: "q23", text: "ما هي المجالات التي تشعر أنك ما زلت بحاجة إلى مزيد من التطوير فيها؟", type: "text" },
      { id: "q24", text: "تقييمك لآلية متابعة التقدم وتقديم الملاحظات خلال هذه المرحلة.", type: "rating" },
      { id: "q25", text: "هل لديك أي ملاحظات أو أفكار إضافية تود مشاركتها؟", type: "text" },
    ]
  }
];

export const leadershipBuildingSurvey: Survey = {
  id: "Leadership_Succession_Building_Phase_Survey",
  name: "تقييم مرحلة البناء والتطوير في رحلة التعاقب القيادي",
  sections: surveyQuestions_Leadership_Building_Survey_25Q_v1,
};

// Fix: Add mock data to resolve import errors.
export const mockUsers: User[] = [
  { id: '1', name: 'Dana Al-Mutairi', email: 'dana@consulting.com', roles: ['CONSULTANT'] },
  { id: '2', name: 'Ahmed Al-Fahad', email: 'ahmed@acme.com', roles: ['ORGANIZATION_ADMIN'], organizationId: 1 },
  { id: '3', name: 'Fatima Al-Marzouq', email: 'fatima@acme.com', roles: ['HR_MANAGER'], organizationId: 1 },
  { id: '4', name: 'Khalid Al-Ghamdi', email: 'khalid@acme.com', roles: ['CANDIDATE'], organizationId: 1, candidateId: 101 },
  { id: '5', name: 'Sultan Al-Otaibi', email: 'sultan@gov.sa', roles: ['ORGANIZATION_ADMIN'], organizationId: 2 },
  { id: '6', name: 'Layla Al-Qahtani', email: 'layla@gov.sa', roles: ['CANDIDATE'], organizationId: 2, candidateId: 102 },
  { id: '7', name: 'Nasser Al-Jasser', email: 'nasser@acme.com', roles: ['SUPERVISOR'], organizationId: 1 },
  { id: '8', name: 'Samira Adel', email: 'samira@acme.com', roles: ['VIEWER'], organizationId: 1 },
  { id: '9', name: 'عبد اللطيف الكندري', email: 'alkandari@mubarra.org', roles: ['CANDIDATE'], organizationId: 4, candidateId: 111 },
];

export const mockOrganizations: Organization[] = [
    {
        id: 1,
        name: "ACME Corporation",
        sector: "Technology",
        type: 'corporate',
        language_pref: 'en',
        maturity_level: 'Maturing',
        stages: journeyConfig.corporate.en,
        orlsAssessment: { governance: 75, culture: 80, systems: 65, resources: 70, strategic_support: 85 },
        insight_history: [
            "Khalid Al-Ghamdi's readiness for the CTO role has now reached 45%.",
            "The Adoption & Engagement Index for 'Building & Development' has been updated to 55%."
        ],
        recommendations: [
            "Candidate LRI scores have plateaued despite milestone completions. Suggest introducing more cross-functional projects to boost 'Competence'.",
            "Reflection log sentiment has declined recently. Recommend targeted check-ins with candidates to address potential roadblocks.",
            "Excellent momentum in LRI scores and positive reflections. Recommend identifying high-performers for advanced mentorship opportunities."
        ],
        auto_pilot_enabled: false,
        institutional_archive: [],
        description: "A leading innovator in cloud solutions and enterprise software.",
        contactInfo: { email: "contact@acme.com", phone: "+1-202-555-0149", address: "123 Tech Way, Silicon Valley, CA" },
        createdAt: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    },
    {
        id: 2,
        name: "الهيئة العامة للبيانات",
        sector: "القطاع الحكومي",
        type: 'government',
        language_pref: 'ar',
        maturity_level: 'Advanced',
        stages: journeyConfig.government.ar,
        orlsAssessment: { governance: 90, culture: 85, systems: 95, resources: 88, strategic_support: 92 },
        insight_history: ["أكملت ليلى القحطاني بنجاح مرحلة 'بناء الكفاءات والتدريب على السياسات'."],
        auto_pilot_enabled: true,
        institutional_archive: [],
        description: "الجهة الحكومية المسؤولة عن تنظيم وإدارة البيانات الوطنية.",
        contactInfo: { email: "info@gda.gov.sa", phone: "+966-11-555-0182", address: "طريق الملك فهد، الرياض" },
        createdAt: new Date(Date.now() - 250 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    },
    {
        id: 3,
        name: "Future Leaders Academy",
        sector: "Education",
        type: 'education',
        language_pref: 'en',
        maturity_level: 'Emerging',
        stages: journeyConfig.education.en,
        orlsAssessment: { governance: 60, culture: 70, systems: 55, resources: 65, strategic_support: 75 },
        createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'inactive',
        contactInfo: { email: "admissions@fla.edu", phone: "+44-20-7946-0958", address: "1 Education Road, London, UK" },
    },
    {
        id: 4,
        name: "مبرة المتميزين",
        sector: "القطاع الخيري",
        type: 'charity',
        language_pref: 'ar',
        maturity_level: 'Emerging',
        stages: journeyConfig.charity.ar,
        orlsAssessment: { governance: 65, culture: 75, systems: 50, resources: 60, strategic_support: 70 },
        insight_history: ["تم إنشاء خطة تطوير جديدة للمرشح عبد اللطيف الكندري."],
        auto_pilot_enabled: false,
        institutional_archive: [],
        description: "مبرة خيرية تهدف إلى دعم المتميزين والموهوبين في مختلف المجالات.",
        contactInfo: { email: "info@mubarra.org", phone: "+965-222-555-01", address: "مدينة الكويت، الكويت" },
        createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        status: 'active',
    }
];

const generateMilestonesForPlan = (orgId: number, lang: Language, type: InstitutionType): JourneyMilestone[] => {
    const stages = journeyConfig[type][lang];
    let idCounter = 0;
    return stages.flatMap(stage => 
        (stage.default_tasks || []).map(taskTitle => ({
            id: Date.now() + (idCounter++),
            title: taskTitle,
            description: `Details for ${taskTitle}`,
            status: 'NotStarted',
            stageCode: stage.code,
            ownerId: '3', // Fatima Al-Marzouq (HR Manager)
        }))
    );
};

export const mockSuccessionPlans: SuccessionPlan[] = [
    {
        id: 1,
        orgId: 1,
        roleTitle: "Chief Technology Officer",
        candidate: { id: 101, name: 'Khalid Al-Ghamdi', currentRole: "Senior Developer" },
        readiness: 45,
        maturity: 55,
        closureStatus: 'pending',
        lriAssessment: { competence: 40, behavior: 50, value_alignment: 60, learning_agility: 30 },
        previousLriAssessment: { competence: 35, behavior: 48, value_alignment: 55, learning_agility: 25 },
        bvi: 65,
        lqm: 70,
        behavioralIndicators: { honesty: 70, respect: 80, innovation: 60, collaboration: 75, responsibility: 65 },
        aiGeneratedPlan: "## Assessment & Planning\n- Analyze current technology stack and team structure.\n- Define the 3-year technology roadmap.\n\n## Building & Development\n- Lead a cross-functional project to implement a new microservice.\n- Mentor two junior developers.\n- Complete an advanced course on cloud architecture.",
        journey: generateMilestonesForPlan(1, 'en', 'corporate'),
        previousMaturity: 50,
    },
    {
        id: 2,
        orgId: 2,
        roleTitle: "مدير إدارة الاستراتيجية",
        candidate: { id: 102, name: 'Layla Al-Qahtani', currentRole: "محلل استراتيجي أول" },
        readiness: 70,
        maturity: 78,
        closureStatus: 'pending',
        lriAssessment: { competence: 75, behavior: 65, value_alignment: 80, learning_agility: 60 },
        bvi: 80,
        lqm: 75,
        behavioralIndicators: { honesty: 85, respect: 75, innovation: 65, collaboration: 80, responsibility: 90 },
        aiGeneratedPlan: "## تحليل الاحتياجات ومواءمة التفويض\n- مراجعة الاستراتيجية الحالية للهيئة وتقديم تقرير.\n- إجراء مقابلات مع رؤساء الأقسام لتحديد الأولويات.\n\n## بناء الكفاءات والتدريب على السياسات\n- حضور ورشة عمل متقدمة في التخطيط الاستراتيجي الحكومي.\n- قيادة فريق عمل لصياغة سياسة جديدة.",
        journey: generateMilestonesForPlan(2, 'ar', 'government'),
        previousMaturity: 72,
    },
    {
        id: 4,
        orgId: 4,
        roleTitle: "رئيس تنفيذي",
        candidate: { id: 111, name: 'عبد اللطيف الكندري', currentRole: "مدير مشاريع" },
        readiness: 25,
        maturity: 10,
        closureStatus: 'pending',
        lriAssessment: { competence: 30, behavior: 25, value_alignment: 40, learning_agility: 15 },
        bvi: 55,
        lqm: 60,
        behavioralIndicators: { honesty: 60, respect: 70, innovation: 50, collaboration: 65, responsibility: 55 },
        aiGeneratedPlan: "## التقييم والتخطيط\n- تحليل الهيكل التنظيمي الحالي للمبرة.\n- بناء مصفوفة أصحاب المصلحة وتحديد أولويات التواصل.\n\n## البناء والتطوير\n- حضور برنامج تدريبي في القيادة التنفيذية للمنظمات غير الربحية.\n- قيادة مبادرة لزيادة الموارد المالية للمبرة بنسبة 15%.",
        journey: generateMilestonesForPlan(4, 'ar', 'charity'),
    }
];

if (mockSuccessionPlans[1]) {
    mockSuccessionPlans[1].journey[0].status = 'Completed';
    mockSuccessionPlans[1].journey[1].status = 'Completed';
    mockSuccessionPlans[1].journey[2].status = 'Completed';
    mockSuccessionPlans[1].journey[3].status = 'InProgress';
}

export const mockReflectionLogs: ReflectionLog[] = [
    { id: 1, user_id: '4', org_id: 1, stage_code: 'STG1', note: "The planning session was very insightful. I have a clearer understanding of the expectations for the CTO role.", sentiment: 'positive', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 2, user_id: '3', org_id: 1, stage_code: 'STG1', note: "Khalid seems engaged, but we need to work on his learning agility for the technical leadership aspects.", sentiment: 'neutral', timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 3, user_id: '6', org_id: 2, stage_code: 'STG2', note: "ورشة العمل كانت ممتازة وأضافت لي الكثير في فهم السياسات الحكومية.", sentiment: 'positive', timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 4, user_id: '5', org_id: 2, stage_code: 'STG2', note: "أظهرت ليلى قدرة عالية على التحليل أثناء صياغة السياسة الجديدة.", sentiment: 'positive', timestamp: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 5, user_id: '4', org_id: 1, stage_code: 'STG2', note: "Struggling a bit with the cloud architecture course, it's more complex than I anticipated.", sentiment: 'negative', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 6, user_id: '9', org_id: 4, stage_code: 'STG1', note: "اجتماع التخطيط الأولي كان مثمراً، أتطلع لبدء مرحلة البناء والتطوير.", sentiment: 'positive', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
    { id: 7, user_id: '1', org_id: 4, stage_code: 'STG1', note: "يُظهر عبد اللطيف حماساً كبيراً، لكنه بحاجة إلى تركيز أكبر على الجانب المالي في قيادة المنظمات غير الربحية.", sentiment: 'neutral', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() }
];


export const translations: Record<Language, Translations> = {
  en: {
    notifications: 'Notifications',
    markAllAsRead: 'Mark all as read',
    noNotifications: 'No new notifications.',
    welcomeGreeting: "Welcome to",
    welcomeJourney: "The Leadership Succession Journey",
    welcomeAdvisorName: "Your Advisor, Mustafa Al-Mosul",
    startExperience: "Start Experience",
    welcomeTitle: 'Succession Planning AI',
    welcomeSubtitle: 'Select your organization to begin.',
    logout: 'Logout',
    logoutConfirmTitle: 'Confirm Logout',
    logoutConfirmMessage: 'Are you sure you want to log out?',
    confirm: 'Confirm',
    globalAccess: 'Global Access',
    role_CONSULTANT: 'Consultant',
    role_ORGANIZATION_ADMIN: 'Organization Admin',
    role_HR_MANAGER: 'HR Manager',
    role_SUPERVISOR: 'Supervisor',
    role_CANDIDATE: 'Leadership Candidate',
    role_VIEWER: 'Viewer',
    appTitle: 'Succession AI',
    selectOrg: 'Select an Organization...',
    dashboard: 'Dashboard',
    overview: 'Overview',
    criticalRoles: 'Critical Roles',
    successorsReady: 'Successors Ready',
    avgLriScore: 'Avg. LRI Score',
    successionPlans: 'Succession Plans',
    role: 'Role',
    candidate: 'Candidate',
    lriScore: 'LRI Score',
    actions: 'Actions',
    view: 'View',
    createNewPlan: 'Create New Plan',
    plannerTitle: 'Design Succession Journey',
    plannerSubtitle: 'Use AI to generate a tailored development plan for a successor.',
    targetRole: 'Target Role Title',
    targetRolePlaceholder: 'e.g., Chief Technology Officer',
    keyCompetencies: 'Key Competencies',
    keyCompetenciesPlaceholder: 'e.g., Strategic Thinking, Technical Leadership, Team Development...',
    potentialCandidate: 'Potential Candidate Name',
    potentialCandidatePlaceholder: 'e.g., Jane Doe',
    generatePlan: 'Generate Plan with AI',
    generating: 'Generating...',
    aiGeneratedPlan: 'AI-Generated Development Plan',
    saveAndClose: 'Save & Close',
    backToDashboard: 'Back to Dashboard',
    journeyMonitorTitle: 'Succession Journey',
    progressIndicators: 'Progress Indicators',
    complete: 'Complete',
    incomplete: 'Incomplete',
    progress: 'Progress',
    copyPlan: 'Copy Plan Text',
    copied: 'Copied!',
    cancel: 'Cancel',
    maturityLevel: 'Maturity Level',
    Emerging: 'Emerging',
    Maturing: 'Maturing',
    Advanced: 'Advanced',
    manageStages: 'Manage Journey Stages',
    editStages: 'Edit Stages',
    stage: 'Stage',
    saveChanges: 'Save Changes',
    defaultTasks: 'Default Tasks for this Stage',
    addTask: 'Add Task',
    taskPlaceholder: 'Enter task description...',
    lriTitle: "Leadership Readiness Index",
    competence: "Competence",
    behavior: "Behavior",
    value_alignment: "Value Alignment",
    learning_agility: "Learning Agility",
    orlsTitle: "Organizational Readiness Level",
    orlsScore: "ORLS Score",
    governance: "Governance",
    culture: "Culture",
    systems: "Systems",
    resources: "Resources",
    strategic_support: "Strategic Support",
    cri: "Change Resistance Index",
    aei: "Adoption & Engagement Index",
    avgCri: "Avg. CRI",
    avgAei: "Avg. AEI",
    reflectionLog: "Reflection Log",
    addReflection: "Add Reflection",
    yourNote: "Your Note...",
    sentiment: "Sentiment",
    positive: "Positive",
    neutral: "Neutral",
    negative: "Negative",
    addNote: "Add Note",
    summarizeReflections: "Summarize Reflections",
    aiSummary: "AI Summary of Reflections",
    summarizing: "Summarizing...",
    journeySnapshot: "Journey Snapshot",
    currentStage: "Current Stage",
    stageTasksStatus: "Stage Tasks",
    noReflections: "No reflections added for this stage yet.",
    crossOrgInsights: "Cross-Organization Insights",
    lowReadinessOrgs: "Low Readiness Organizations",
    topRisks: "Top Organizational Risks (Low ORLS)",
    commonTrainingGaps: "Common Training Gaps (LRI)",
    avgLri: "Avg. LRI",
    avgOrls: "Avg. ORLS",
    lowestLriDimension: "Lowest Avg. LRI Dimension",
    noData: "No relevant data to display.",
    tasksAndMetrics: "Tasks & Metrics",
    english: "English",
    arabic: "العربية",
    insightHistoryTitle: "Recent Insights",
    noInsights: "No new insights to show at this time.",
    insight_stage_completed: "{candidateName} has successfully completed the '{stageName}' stage.",
    insight_lri_improvement: "{candidateName} is showing a {change}% improvement in {dimension}.",
    insight_readiness_milestone: "{candidateName}'s readiness for the {roleTitle} role has now reached {readiness}%.",
    insight_cri_update: "The Change Resistance Index for '{stageName}' has been updated to {value}%.",
    insight_aei_update: "The Adoption & Engagement Index for '{stageName}' has been updated to {value}%.",
    insight_lqm_update: "{candidateName}'s Leadership Quality Momentum is now {lqm}% following a new reflection.",
    insight_daily_summary: "Daily Summary: {summary}",
    insight_yearly_summary: "Yearly Archive Summary ({year}): Avg LRI: {avgLri}%, Avg BVI: {avgBvi}, ORLS: {orlsScore}%, Total Completed Plans: {completedPlans}.",
    insight_lessons_learned: "Lessons learned from stage '{stageName}' for {candidateName}: '{lessons}'",
    journeyTimelinePreview: "Journey Timeline (Preview)",
    backToMonitor: "Back to Monitor",
    backToTimeline: "Back to Timeline",
    bvi: "Behavioral Velocity Index",
    lqm: "Leadership Quality Momentum",
    valueMirror: "Value Mirror",
    consultingDashboardTitle: "Consulting House Dashboard",
    globalMetrics: "Global Metrics",
    avgBvi: "Avg. BVI",
    orgsWithLowReadiness: "Orgs with Low Readiness",
    topValuesInAction: "Top Values in Action",
    value_collaboration: "Collaboration",
    value_learning: "Learning",
    value_initiative: "Initiative",
    value_resilience: "Resilience",
    value_honesty: "Honesty",
    value_respect: "Respect",
    value_innovation: "Innovation",
    value_responsibility: "Responsibility",
    globalView: "Global View",
    recommendations: "Recommendations",
    recommendationTitle: "Continuous Learning Loop",
    reco_sentiment_decline: "Reflection log sentiment has declined recently. Recommend targeted check-ins with candidates to address potential roadblocks.",
    reco_lri_stagnant: "Candidate LRI scores have plateaued despite milestone completions. Suggest introducing more cross-functional projects to boost '{dimension}'.",
    reco_low_aei: "Adoption & Engagement Index (AEI) for stage '{stageName}' is low. Recommend reviewing stage tasks for relevance and clarity.",
    reco_positive_trend: "Excellent momentum in LRI scores and positive reflections. Recommend identifying high-performers for advanced mentorship opportunities.",
    reco_value_focus: "There's a strong focus on '{value}' in reflections. Leverage this by creating a knowledge-sharing session led by candidates.",
    reco_orls_low: "Organizational Readiness (ORLS) is below 60%. Recommend conducting an 'Institutional Readiness Workshop' to align on governance and resources.",
    reco_lri_low: "Candidate {candidateName}'s LRI score is below 50%. Recommend enrollment in a 'Leadership Bootcamp' to accelerate core competency development.",
    reco_aei_decline: "Adoption & Engagement (AEI) has declined for 3 consecutive cycles. Recommend deploying a 'Motivation Pulse Survey' to identify engagement drivers.",
    switchRole: "Switch Role",
    viewingAs: "Viewing as:",
    aiChatbotTitle: "AI Advisor",
    chatbotPlaceholder: "Ask about succession plans, LRI scores, etc...",
    send: "Send",
    institutionalConfirmation: "Institutional Confirmation",
    expectedResults: "Institution's Expectations",
    actualResults: "Actual Results",
    gapAnalysis: "Gap Analysis",
    generateAnalysis: "Generate Gap Analysis",
    generatingAnalysis: "Generating...",
    readinessIndex: "Leadership Readiness Index",
    maturityIndex: "Leadership Maturity Index",
    stageClosure_leadershipCandidate: 'Leadership Candidate',
    aiBehavioralInsight: "AI Behavioral Insight",
    generateInsight: "Generate Insight",
    generatingInsight: "Generating...",
    regenerateInsight: "Regenerate",
    generateInsightDescription: "Analyze behavioral scores and reflections to get a coaching insight.",
    stageClosure_lessonsLearned: 'Lessons Learned from this Stage',
    toast_autosave_success: 'Note saved successfully.',
    toast_archive_title: 'Year-End Archive',
    toast_archive_complete: 'Year-end archive for {orgName} completed successfully.',
    error: 'An Error Occurred',
    stageClosure_roleContextError: 'User role context is missing. Cannot display this page. Please go back and try again.',
    selectYourRole: 'Select your role to begin...',
    stageClosure_signed: 'Signed',
    stageClosure_waitingForCandidate: 'Waiting for Candidate',
    stageClosure_waitingForConsultant: 'Waiting for Consultant',
    toast_archive_success_title: 'Stage Data Archived',
    toast_archive_success_subtitle: 'Closure data for stage \'{stageName}\' has been successfully archived.',
    viewArchive: 'View Archive',
    institutionalArchive: 'Institutional Archive',
    archiveDate: 'Archive Date',
    plan: 'Plan',
    details: 'Details',
    noArchivedData: 'No archived data found for this organization.',
    archiveDetails: 'Archive Details',
    stageClosure_signature_candidate: 'Candidate',
    stageClosure_signature_consultant: 'Consultant',
    stageClosure_signature_orgAdmin: 'Org. Admin',
    none: 'None',
    notSigned: 'Not Signed',
    finalRating: 'Final Rating of Stage Experience',
    stageClosure_processReview: 'Process Review',
    stageClosure_clarityOfGoals: 'Clarity of Stage Goals',
    stageClosure_resourceQuality: 'Quality of Resources & Tools',
    stageClosure_feedbackEffectiveness: 'Effectiveness of Feedback & Guidance',
    topImprovementThemes: 'Top Improvement Themes',
    viewCandidatePlan: 'View Plan',
    autoPilotMode: 'Auto-Pilot Mode',
    autoPilotDescription: 'When enabled, the system will automatically run learning loops, generate reports, and manage insights based on AI analysis. This requires an organizational readiness (ORLS) score of at least 90%.',
    autoPilotRequirement: 'ORLS score must be ≥ 90% to enable.',
    autoPilotOverride: 'Consulting Admin can override ORLS requirement.',
    suggestedImprovementPoints: 'Suggested Improvement Points',
    improvementArea: 'Improvement Area',
    recommendationText: 'Recommendation Text',
    priority: 'Priority',
    priority_High: 'High',
    priority_Medium: 'Medium',
    priority_Low: 'Low',
    addRecommendation: 'Add Recommendation',
    feedbackModalTitle: 'Feedback for {candidateName}',
    consultantNotes: 'Consultant Notes',
    sendFeedback: 'Send Feedback',
    candidateFeedbackThread: 'Candidate Feedback Thread',
    noFeedbackForStage: 'No feedback has been shared for this stage yet.',
    exportToPdf: 'Export to PDF',
    from: 'From',
    candidateReply: 'Your Reply',
    addYourReply: 'Add your reply...',
    sendReply: 'Send Reply',
    feedbackStatus: 'Status',
    status_AwaitingReply: 'Awaiting Reply',
    status_Discussed: 'Discussed',
    markAsDiscussed: 'Mark as Discussed',
    initialImprovementPlan: 'Initial Improvement & Development Plan',
    exportDevelopmentPdf: 'Export Development PDF',
    coreDevelopmentAxis: 'Core Axis',
    readinessSummary: 'Readiness Summary',
    candidateReadiness: 'Candidate Readiness',
    orgReadiness: 'Organizational Readiness',
    viewDetailsFor: 'View details for',
    estimatedDuration: 'Est. Duration',
    days: 'Days',
    shareFeedback: 'Share Feedback',
    startEvaluation: 'Start Evaluation',
    valuesDashboardTitle: 'Values Dashboard',
    behavioralIndicators: 'Behavioral Indicators',
    honesty: 'Honesty',
    respect: 'Respect',
    innovation: 'Innovation',
    collaboration: 'Collaboration',
    responsibility: 'Responsibility',
    stage_not_found: 'Stage not found',
    go_back: 'Go Back',
    evaluationStageReadOnlyMessage: 'This stage is for evaluation. Candidate inputs are read-only after submission.',
    tasks: 'Tasks',
    task_name: 'Task Name',
    owner: 'Owner',
    duration: 'Duration',
    template: 'Template',
    status: 'Status',
    no_owner: 'N/A',
    no_template: 'N/A',
    view_template: 'View',
    status_NotStarted: 'Not Started',
    status_InProgress: 'In Progress',
    status_Completed: 'Completed',
    status_Delayed: 'Delayed',
    status_Cancelled: 'Cancelled',
    noTasksForStage: 'No specific tasks are defined for this stage.',
    closeStage: 'Close Stage',
    evaluationForStage: 'Evaluation for stage: {stageName}',
    previous: 'Previous',
    next: 'Next',
    finishEvaluation: 'Finish Evaluation',
    surveyBuildingPhaseDescription: 'This survey helps us understand your experience during the Building & Development phase. Your feedback is valuable for continuous improvement.',
    evaluateBuildingPhase: 'Evaluate Building Phase',
    planDataNotAvailable: 'Plan data is not available.',
    candidateOverview: 'Candidate Overview',
    aiRecommendations: 'AI Recommendations',
    noRecommendations: 'No specific recommendations at this time.',
    developmentActions: 'Development Actions',
    overallProgress: 'Overall Progress',
    upcomingTasks: 'Upcoming Tasks',
    noUpcomingTasks: 'All tasks for the current stage are complete!',
    coachingNotes: 'Recent Coaching Notes',
    noCoachingNotes: 'No coaching notes have been added recently.',
    stageClosureTitle: 'Stage Closure: {stageName}',
    stageSummary: 'Stage Summary',
    stageClosure_leadershipMaturity: 'Leadership Maturity Snapshot',
    stageClosure_beforeStage: 'Before stage',
    lessonsLearnedPlaceholder: 'Record any observations, successes, or challenges from this stage...',
    stageClosure_signatures: 'Signatures',
    stageClosure_role: 'Role',
    stageClosure_action: 'Action',
    stageClosure_consultingHouseAdmin: 'Consulting House Admin',
    stageClosure_organizationAdmin: 'Organization Admin',
    stageClosure_signedOn: 'Signed on',
    stageClosure_signaturePending: 'Signature Pending',
    stageClosure_signNow: 'Sign Now',
    stageClosure_signatureNotAllowed: 'Not Allowed',
    confirmClosure: 'I confirm that all information is accurate and the stage is ready for closure.',
    stageClosure_exportSummary: 'Export Summary',
    confirmAndCloseStage: 'Confirm & Close Stage',
    settings: 'Settings',
    changeLanguage: 'Change Language',
    viewValuesDashboard: 'Values Dashboard',
    organizationalOverview: 'Organizational Overview',
    highCriAlert: 'High Change Resistance Index detected.',
    avgReadiness: 'Avg. Readiness',
    topValues: 'Top Values',
    monthlyReports: 'Pending Monthly Reports',
    viewReport: 'View Report',
    markReviewed: 'Mark as Reviewed',
    noPendingReports: 'No pending reports to review.',
    globalTopImprovementThemes: 'Global Top Improvement Themes',
    reportDetails: 'Report Details',
    downloadPdf: 'Download PDF',
    close: 'Close',
    analysisComplete: 'Daily analysis complete!',
    analyzing: 'Analyzing...',
    runDailyAnalysis: 'Run Daily Analysis',
    liveJourneyDashboard: 'Live Journey Dashboard',
    backToJourney: 'Back to Journey',
    journeyCompletedMessage: 'Journey Completed!',
    timelineSummary: 'Timeline Summary',
    keyInsights: 'Key Insights from the Journey',
    noJourneyInsights: 'No specific insights were recorded for this candidate during the journey.',
    exportSummary: 'Export Summary',
    setupReadinessTitle: 'Let\'s set up your experience',
    setupReadinessSubtitle: 'A few questions to tailor the system to your needs.',
    userTypeLeader: 'Leadership Candidate',
    userTypeHR: 'HR / Project Manager',
    userTypeInstitution: 'Institution Decision Maker',
    userTypeConsultant: 'Consultant',
    readinessQuestion1: 'How familiar are you with succession planning concepts?',
    readinessAnswerLow: 'Beginner',
    readinessAnswerMedium: 'Intermediate',
    readinessAnswerHigh: 'Expert',
    readinessQuestion2: 'Does your institution have an existing succession plan?',
    readinessAnswerNo: 'No, we are starting from scratch',
    readinessAnswerInProgress: 'It\'s under development',
    readinessAnswerYes: 'Yes, we have a formal plan',
    submitAndContinue: 'Submit & Continue',
    surveySubmittedTitle: 'Survey Submitted',
    surveySubmittedSubtitle: 'Thank you for your valuable feedback!',
    monthlyReportGenerated: 'New monthly report generated for {orgName}.',
    stageClosedTitle: 'Stage Closed',
    stageClosedSubtitle: 'Individual stage \'{stageName}\' has been closed. Your feedback has been saved.',
    pendingRequirementsTitle: 'Pending Requirements',
    validation_tasksNotCompleted: 'At least 90% of stage tasks must be completed.',
    validation_lessonsLearnedMissing: 'Lessons Learned must be filled out.',
    validation_finalRatingMissing: 'A Final Rating for the stage experience must be provided.',
    validation_processRatingsMissing: 'All Process Review items must be rated.',
    toast_readyForReview_title: 'Ready for Review',
    toast_readyForReview_subtitle: '{candidateName}\'s stage closure is fully signed and is now ready for final review and archival.',
    validation_minReadyCandidatesNotMet: 'At least 80% of candidates must have a readiness score of 85% or higher.',
    validation_pendingReviews: 'All other plans pending review must be approved or archived before proceeding.',
    stageClosureDashboardTitle: 'Institutional Review Dashboard',
    closureStatus: 'Status',
    approveCandidateClosure: 'Approve Closure',
    returnCandidateForFix: 'Return for Review',
    toast_approve_success_title: 'Closure Approved',
    toast_approve_success_subtitle: 'The closure for {candidateName} has been successfully approved.',
    toast_return_success_title: 'Closure Returned',
    toast_return_success_subtitle: 'The closure for {candidateName} has been returned for further review.',
    toast_stage_closure_approved_title: 'Stage Closure Approved',
    toast_stage_closure_approved_subtitle: "Closure for '{stageName}' has been approved and archived.",
    toast_stage_closure_approved_candidate_subtitle: "Your stage '{stageName}' has been approved! Your journey continues.",
    insight_stage_archived: "Institutional stage '{stageName}' for {candidateName} has been formally closed and archived.",
    status_pending: 'Pending',
    status_readyForReview: 'Ready for Review',
    status_archived: 'Archived',
    toast_closure_returned_title: 'Closure Returned',
    toast_closure_returned_subtitle: 'The closure for {candidateName} has been returned for review. Signatures have been reset.',
    stageClosure_pendingFinalApproval: 'This stage closure is now pending final approval on the Institutional Review Dashboard.',
    stageClosure_archivedMessage: 'This stage has been closed and all associated data has been permanently archived.',
    overallJourneyProgress: 'Overall Journey Progress',
    tooltip_lri: 'Leadership Readiness Index (LRI): Measures the candidate\'s readiness based on competence, behavior, value alignment, and learning agility.',
    tooltip_maturity: 'Leadership Maturity Index: Measures the percentage of completed milestones in the development journey.',
    tooltip_bvi: 'Behavioral Velocity Index (BVI): Tracks the momentum of behavioral development based on task completions and reflections.',
    tooltip_lqm: 'Leadership Quality Momentum (LQM): Reflects the quality and sentiment of the candidate\'s engagement and reflections.',
    executiveSummary: 'Executive Summary',
    remainingTasks: 'Remaining Tasks',
    completionTimeline: 'Completion Timeline',
    stage_summary_STG1: 'This initial stage focuses on foundational assessment and strategic planning to align the candidate with the organization\'s future leadership needs.',
    stage_summary_STG2: 'The core development phase where the candidate actively engages in qualification programs, mentorship, and practical application to build key leadership competencies.',
    stage_summary_STG3: 'An evaluation-focused stage where the candidate applies learned skills in real-world scenarios, and their performance and the training\'s effectiveness are assessed.',
    stage_summary_STG4: 'The final stage ensures a smooth transition and long-term success by focusing on post-transition follow-up, impact monitoring, and continuous improvement.',
    kpi: 'Key Performance Indicator',
    finalReadinessDelta: 'Final Readiness Delta',
    kpiDescription: "Change in the candidate's LRI score during this stage.",
    targetVsActual: 'Target vs. Actual',
    plannedDuration: 'Planned Duration',
    actualDuration: 'Actual Duration',
    plannedDurationDescription: 'The estimated time for this stage based on readiness metrics.',
    actualDurationDescription: 'The simulated time taken to complete all tasks in this stage.',
    recommendationsForNextStage: 'Recommendations for Next Stage',
    generateRecommendations: 'Generate Recommendations',
    generatingRecommendations: 'Generating...',
    comprehensiveDashboard: 'Comprehensive Dashboard',
    manageOrganizations: 'Manage Organizations',
    candidates: 'Candidates',
    manageCandidates: 'Manage Candidates',
    total: 'Total',
    active: 'Active',
    completed: 'Completed',
    template_standard_name: 'Standard Leadership Track',
    template_standard_desc: 'A balanced plan for emerging corporate leaders.',
    template_exec_name: 'Executive Fast Track',
    template_exec_desc: 'An accelerated plan for high-potential executives.',
    template_gov_name: 'Public Sector Leadership',
    template_gov_desc: 'Comprehensive development for government roles.',

    // New keys for localization
    unitActivities: 'Unit Activities',
    learningMaterialChangeMgmt: 'Learning Material: Change Management',
    stakeholderMapActivity: 'Practical Activity: Stakeholder Map',
    professionalReflection: 'Professional Reflection',
    shortAssessment: 'Short Assessment',
    uploadDeliverables: 'Upload Deliverables',
    buildingPhaseIntro: 'Intro to Building Phase',
    contentPlaceholder: 'Content display area (Placeholder)',
    generateMcq: '✨ Generate Multiple-Choice Questions',
    generatingMcqs: 'Generating questions...',
    checkAnswer: 'Check Answer',
    correctAnswer: 'Correct answer!',
    incorrectAnswer: 'Incorrect answer, try again.',
    stakeholderMapTaskDesc: 'Execute the following activity: Draw a stakeholder map for your leadership project.',
    submitTask: 'Submit Task',
    writeYourReflection: 'Write your reflection on what you learned in this stage:',
    myThoughtsPlaceholder: 'My thoughts on this experience...',
    uploadDeliverable: 'Upload Deliverable',
    quickAssessment: 'Quick Assessment:',
    questionNum: 'Question {num}',
    buildingPhaseIntroTitle: 'Introduction to the Building & Development Phase',
    buildingPhaseIntroDesc: 'In this phase, you will focus on developing core leadership competencies through a series of interactive activities and practical tasks. Prepare for an intensive learning journey that will help refine your skills and prepare you for upcoming responsibilities.',
    activityInteraction: 'Interaction on this Activity',
    writeYourNotesPlaceholder: 'Write your notes...',
    commentingAs: 'Comment as...',
    role_candidate_short: 'Candidate',
    role_consultant_short: 'Consultant',
    role_org_admin_short: 'Org Admin',
    rateActivityUsefulness: 'Rate the usefulness of this activity:',
    createNewPlanNewFlow: 'Create Plan (New Flow)',
    noSuccessionPlansFound: 'No succession plans found for this view.',
    clickToGetStarted: 'Click "{createNewPlan}" to get started.',
    quickCandidateSwitch: 'Quick Candidate Switch',
    valuesDashboard: 'Values Dashboard',
    alert_fillAllFields: 'Please fill all fields',
    toBeDefined: 'To be defined',
    generatedPlanWillAppearHere: 'Your generated plan will appear here.',
    alert_settingsClicked: 'Settings clicked',
    alert_noDemoUserForRole: 'No demo user found for this role.',
    confirm_deleteCandidate: 'Are you sure you want to delete this candidate?',
    toast_planCreated_title: 'Plan Created',
    toast_planCreated_subtitle: 'Successfully created a new plan for {candidateName}.',
    loadingConsultantDashboard: 'Loading comprehensive dashboard...',
    loadingStageData: 'Loading stage data...',
    backToList: 'Back to List',
    editOrg: 'Edit: {name}',
    addNewOrg: 'Add New Organization',
    orgName: 'Organization Name',
    inactive: 'Inactive',
    description: 'Description',
    logoUrl: 'Logo URL',
    contactInfo: 'Contact Info',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    alert_orgNameRequired: 'Organization name is required.',
    creationDate: 'Creation Date',
    candidateCount: 'Candidate Count',
    noOrgsFound: 'No organizations found.',
    clickAddNewOrg: 'Click "Add New Organization" to get started.',
    edit: 'Edit',
    generalInfo: 'General Info',
    noDescription: 'No description.',
    statistics: 'Statistics',
    activeCandidate: 'Active Candidate',
    candidateList: 'Candidate List',
    noCandidatesForOrg: 'No candidates for this organization.',
    addCandidate: 'Add Candidate',
    searchByNameOrPosition: 'Search by name or position...',
    filterByStatus: 'Filter by status',
    filterByDepartment: 'Filter by department',
    clearFilters: 'Clear Filters',
    candidateName: 'Candidate Name',
    completionPercentage: 'Completion Percentage',
    monitorJourney: 'Monitor Journey',
    delete: 'Delete',
    alert_nameAndTargetRequired: 'Name and Target Position are required fields.',
    editCandidateData: 'Edit Candidate Data',
    addNewCandidate: 'Add New Candidate',
    fullName: 'Full Name',
    currentPosition: 'Current Position',
    department: 'Department',
    profilePictureUrl: 'Profile Picture URL',
    save: 'Save',
    paused: 'Paused',
    archived: 'Archived',
    lastActivity: 'Last Activity',
    // StageDetailScreen keys
    viewStageDashboard: 'View Stage Dashboard',
    advancedStageManagement: 'Advanced Stage Management',
    step: 'Step',
    goal: 'Goal',
    alert: 'Alert',
    category: 'Category',
    targetDate: 'Target Date',
    sendAlert: 'Send',
    evaluateStageExperience: 'Evaluate Stage Experience',
    addAdvancedStepTitle: 'Add New Step for Advanced Stage Management',
    addAdvancedStep: 'Add Step',
    stepCategory: 'Step Category',
    targetCompletionDate: 'Target Completion Date',
    advancedStepStatus_NotStarted: 'Not Started',
    advancedStepStatus_InProgress: 'In Progress',
    advancedStepStatus_Completed: 'Completed',
    stepCategory_operational: 'Operational',
    stepCategory_developmental: 'Developmental',
    stepCategory_followup: 'Follow-up',
    raci_org_admin: 'Organization Admin',
    raci_project_manager: 'Project Manager',
    raci_consultant: 'Consultant',
    raci_candidate: 'Candidate',
    raci_none: '-',
    alertSentTitle: 'Alert Sent',
    alertSentSubtitle: 'Alert for step "{stepName}" has been sent.',
    unauthorized: 'Unauthorized',
    unauthorized_add_step: 'You do not have permission to add operational steps.',
    incomplete_data: 'Incomplete Data',
    incomplete_data_add_step: 'Please fill in the Step and Goal fields.',
    error_add_step: 'Could not save the step, please try again.',
  },
  ar: {
    notifications: 'الإشعارات',
    markAllAsRead: 'تحديد الكل كمقروء',
    noNotifications: 'لا توجد إشعارات جديدة.',
    welcomeGreeting: "أهلاً بك في",
    welcomeJourney: "رحلة التعاقب القيادي",
    welcomeAdvisorName: "مستشارك، مصطفى الموصل",
    startExperience: "ابدأ التجربة",
    welcomeTitle: 'الذكاء الاصطناعي لتخطيط التعاقب الوظيفي',
    welcomeSubtitle: 'اختر مؤسستك للبدء.',
    logout: 'تسجيل الخروج',
    logoutConfirmTitle: 'تأكيد تسجيل الخروج',
    logoutConfirmMessage: 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
    confirm: 'تأكيد',
    globalAccess: 'وصول شامل',
    role_CONSULTANT: 'مستشار بيت الخبرة',
    role_ORGANIZATION_ADMIN: 'مسؤول المؤسسة',
    role_HR_MANAGER: 'مدير الموارد البشرية',
    role_SUPERVISOR: 'مشرف مباشر',
    role_CANDIDATE: 'مرشح قيادي',
    role_VIEWER: 'مطّلع',
    appTitle: 'التعاقب القيادي',
    selectOrg: 'اختر مؤسسة...',
    dashboard: 'لوحة التحكم',
    overview: 'نظرة عامة',
    criticalRoles: 'الوظائف الحرجة',
    successorsReady: 'الخلفاء الجاهزون',
    avgLriScore: 'متوسط مؤشر الجاهزية',
    successionPlans: 'خطط التعاقب',
    role: 'الوظيفة',
    candidate: 'المرشح',
    lriScore: 'مؤشر الجاهزية',
    actions: 'الإجراءات',
    view: 'عرض',
    createNewPlan: 'إنشاء خطة جديدة',
    plannerTitle: 'تصميم رحلة التعاقب',
    plannerSubtitle: 'استخدم الذكاء الاصطناعي لإنشاء خطة تطوير مخصصة لخليفة.',
    targetRole: 'المسمى الوظيفي المستهدف',
    targetRolePlaceholder: 'مثال: الرئيس التنفيذي للتقنية',
    keyCompetencies: 'الكفاءات الرئيسية',
    keyCompetenciesPlaceholder: 'مثال: التفكير الاستراتيجي، القيادة التقنية، تطوير الفريق...',
    potentialCandidate: 'اسم المرشح المحتمل',
    potentialCandidatePlaceholder: 'مثال: سارة عبدالله',
    generatePlan: 'أنشئ الخطة بالذكاء الاصطناعي',
    generating: 'جاري الإنشاء...',
    aiGeneratedPlan: 'خطة التطوير المنشأة بواسطة الذكاء الاصطناعي',
    saveAndClose: 'حفظ وإغلاق',
    backToDashboard: 'العودة للوحة التحكم',
    journeyMonitorTitle: 'رحلة التعاقب',
    progressIndicators: 'مؤشرات التقدم',
    complete: 'مكتمل',
    incomplete: 'غير مكتمل',
    progress: 'التقدم',
    copyPlan: 'نسخ نص الخطة',
    copied: 'تم النسخ!',
    cancel: 'إلغاء',
    maturityLevel: 'مستوى النضج',
    Emerging: 'ناشئ',
    Maturing: 'ناضج',
    Advanced: 'متقدم',
    manageStages: 'إدارة مراحل الرحلة',
    editStages: 'تعديل المراحل',
    stage: 'المرحلة',
    saveChanges: 'حفظ التغييرات',
    defaultTasks: 'المهام الافتراضية لهذه المرحلة',
    addTask: 'إضافة مهمة',
    taskPlaceholder: 'أدخل وصف المهمة...',
    lriTitle: "مؤشر جاهزية القيادة",
    competence: "الكفاءة",
    behavior: "السلوك",
    value_alignment: "توافق القيم",
    learning_agility: "مرونة التعلم",
    orlsTitle: "مستوى الجاهزية المؤسسية",
    orlsScore: "نتيجة ORLS",
    governance: "الحوكمة",
    culture: "الثقافة",
    systems: "الأنظمة",
    resources: "الموارد",
    strategic_support: "الدعم الاستراتيجي",
    cri: "مؤشر مقاومة التغيير",
    aei: "مؤشر التبني والمشاركة",
    avgCri: "متوسط CRI",
    avgAei: "متوسط AEI",
    reflectionLog: "سجل التأملات",
    addReflection: "إضافة تأمل",
    yourNote: "ملاحظتك...",
    sentiment: "المشاعر",
    positive: "إيجابي",
    neutral: "محايد",
    negative: "سلبي",
    addNote: "إضافة ملاحظة",
    summarizeReflections: "تلخيص التأملات",
    aiSummary: "ملخص الذكاء الاصطناعي للتأملات",
    summarizing: "جاري التلخيص...",
    journeySnapshot: "لمحة عن الرحلة",
    currentStage: "المرحلة الحالية",
    stageTasksStatus: "مهام المرحلة",
    noReflections: "لم تتم إضافة تأملات لهذه المرحلة بعد.",
    crossOrgInsights: "رؤى شاملة للمؤسسات",
    lowReadinessOrgs: "المؤسسات ذات الجاهزية المنخفضة",
    topRisks: "أبرز المخاطر المؤسسية (ORLS منخفض)",
    commonTrainingGaps: "فجوات التدريب الشائعة (LRI)",
    avgLri: "متوسط LRI",
    avgOrls: "متوسط ORLS",
    lowestLriDimension: "أدنى أبعاد LRI",
    noData: "لا توجد بيانات ذات صلة لعرضها.",
    tasksAndMetrics: "المهام والمقاييس",
    english: "English",
    arabic: "العربية",
    insightHistoryTitle: "أحدث الرؤى",
    noInsights: "لا توجد رؤى جديدة لعرضها في الوقت الحالي.",
    insight_stage_completed: "أكمل {candidateName} بنجاح مرحلة '{stageName}'.",
    insight_lri_improvement: "يظهر {candidateName} تحسنًا بنسبة {change}٪ في {dimension}.",
    insight_readiness_milestone: "وصلت جاهزية {candidateName} لمنصب {roleTitle} الآن إلى {readiness}٪.",
    insight_cri_update: "تم تحديث مؤشر مقاومة التغيير لمرحلة '{stageName}' إلى {value}٪.",
    insight_aei_update: "تم تحديث مؤشر التبني والمشاركة لمرحلة '{stageName}' إلى {value}٪.",
    insight_lqm_update: "زخم جودة القيادة لـ {candidateName} هو الآن {lqm}٪ بعد تأمل جديد.",
    insight_daily_summary: "الملخص اليومي: {summary}",
    insight_yearly_summary: "ملخص الأرشيف السنوي ({year}): متوسط LRI: {avgLri}٪، متوسط BVI: {avgBvi}، ORLS: {orlsScore}٪، إجمالي الخطط المكتملة: {completedPlans}.",
    insight_lessons_learned: "الدروس المستفادة من مرحلة '{stageName}' للمرشح {candidateName}: '{lessons}'",
    journeyTimelinePreview: "الجدول الزمني للرحلة (معاينة)",
    backToMonitor: "العودة للمراقبة",
    backToTimeline: "العودة للجدول الزمني",
    bvi: "مؤشر سرعة السلوك",
    lqm: "زخم جودة القيادة",
    valueMirror: "مرآة القيم",
    consultingDashboardTitle: "لوحة تحكم بيت الخبرة",
    globalMetrics: "المقاييس الشاملة",
    avgBvi: "متوسط BVI",
    orgsWithLowReadiness: "المؤسسات ذات الجاهزية المنخفضة",
    topValuesInAction: "أبرز القيم الممارسة",
    value_collaboration: "التعاون",
    value_learning: "التعلم",
    value_initiative: "المبادرة",
    value_resilience: "المرونة",
    value_honesty: "الأمانة",
    value_respect: "الاحترام",
    value_innovation: "الابتكار",
    value_responsibility: "المسؤولية",
    globalView: "عرض شامل",
    recommendations: "التوصيات",
    recommendationTitle: "حلقة التعلم المستمر",
    reco_sentiment_decline: "انخفضت معنويات سجل التأملات مؤخرًا. يوصى بإجراء متابعات مستهدفة مع المرشحين لمعالجة العوائق المحتملة.",
    reco_lri_stagnant: "استقرت درجات LRI للمرشحين على الرغم من إكمال المهام. يُقترح تقديم المزيد من المشاريع متعددة الوظائف لتعزيز '{dimension}'.",
    reco_low_aei: "مؤشر التبني والمشاركة (AEI) لمرحلة '{stageName}' منخفض. يوصى بمراجعة مهام المرحلة للتأكد من ملاءمتها ووضوحها.",
    reco_positive_trend: "زخم ممتاز في درجات LRI والتأملات الإيجابية. يوصى بتحديد أصحاب الأداء المتميز لفرص توجيه متقدمة.",
    reco_value_focus: "هناك تركيز قوي على '{value}' في التأملات. استفد من ذلك من خلال إنشاء جلسة لتبادل المعرفة بقيادة المرشحين.",
    reco_orls_low: "الجاهزية المؤسسية (ORLS) أقل من 60%. يوصى بعقد 'ورشة عمل الجاهزية المؤسسية' للمواءمة بشأن الحوكمة والموارد.",
    reco_lri_low: "درجة LRI للمرشح {candidateName} أقل من 50%. يوصى بتسجيله في 'معسكر تدريب القيادة' لتسريع تطوير الكفاءات الأساسية.",
    reco_aei_decline: "انخفض مؤشر التبني والمشاركة (AEI) لثلاث دورات متتالية. يوصى بنشر 'استبيان نبض التحفيز' لتحديد دوافع المشاركة.",
    switchRole: "تبديل الدور",
    viewingAs: "العرض بصفتك:",
    aiChatbotTitle: "المستشار الذكي",
    chatbotPlaceholder: "اسأل عن خطط التعاقب، درجات LRI، إلخ...",
    send: "إرسال",
    institutionalConfirmation: "التأكيد المؤسسي",
    expectedResults: "توقعات المؤسسة",
    actualResults: "النتائج الفعلية",
    gapAnalysis: "تحليل الفجوة",
    generateAnalysis: "توليد تحليل الفجوة",
    generatingAnalysis: "جاري التوليد...",
    readinessIndex: "مؤشر الجاهزية القيادية",
    maturityIndex: "مؤشر النضج القيادي",
    stageClosure_leadershipCandidate: 'المرشح القيادي',
    aiBehavioralInsight: "الرؤية السلوكية بالذكاء الاصطناعي",
    generateInsight: "توليد رؤية",
    generatingInsight: "جاري التوليد...",
    regenerateInsight: "إعادة التوليد",
    generateInsightDescription: "حلل المؤشرات السلوكية والتأملات للحصول على رؤية تدريبية.",
    stageClosure_lessonsLearned: 'الدروس المستفادة من هذه المرحلة',
    toast_autosave_success: 'تم حفظ الملاحظة بنجاح.',
    toast_archive_title: 'الأرشفة السنوية',
    toast_archive_complete: 'تم إتمام الأرشفة بنجاح لمؤسسة {orgName}.',
    error: 'حدث خطأ',
    stageClosure_roleContextError: 'معلومات دور المستخدم غير متوفرة. لا يمكن عرض هذه الصفحة. يرجى الرجوع والمحاولة مرة أخرى.',
    selectYourRole: 'اختر دورك للبدء...',
    stageClosure_signed: 'تم التوقيع',
    stageClosure_waitingForCandidate: 'بانتظار المرشح',
    stageClosure_waitingForConsultant: 'بانتظار المستشار',
    toast_archive_success_title: 'تمت أرشفة بيانات المرحلة',
    toast_archive_success_subtitle: 'تمت أرشفة بيانات إغلاق مرحلة \'{stageName}\' بنجاح.',
    viewArchive: 'عرض الأرشيف',
    institutionalArchive: 'الأرشيف المؤسسي',
    archiveDate: 'تاريخ الأرشفة',
    plan: 'الخطة',
    details: 'التفاصيل',
    noArchivedData: 'لا توجد بيانات مؤرشفة لهذه المؤسسة.',
    archiveDetails: 'تفاصيل الأرشيف',
    stageClosure_signature_candidate: 'المرشح',
    stageClosure_signature_consultant: 'المستشار',
    stageClosure_signature_orgAdmin: 'مسؤول المؤسسة',
    none: 'لا يوجد',
    notSigned: 'لم يتم التوقيع',
    finalRating: 'التقييم النهائي لتجربة المرحلة',
    stageClosure_processReview: 'مراجعة العملية',
    stageClosure_clarityOfGoals: 'وضوح أهداف المرحلة',
    stageClosure_resourceQuality: 'جودة الموارد والأدوات',
    stageClosure_feedbackEffectiveness: 'فعالية الملاحظات والتوجيه',
    topImprovementThemes: 'أبرز محاور التحسين',
    viewCandidatePlan: 'عرض الخطة',
    autoPilotMode: 'وضع الطيار الآلي',
    autoPilotDescription: 'عند التمكين، سيقوم النظام تلقائيًا بتشغيل حلقات التعلم وإنشاء التقارير وإدارة الرؤى بناءً على تحليل الذكاء الاصطناعي. يتطلب هذا درجة جاهزية تنظيمية (ORLS) لا تقل عن 90٪.',
    autoPilotRequirement: 'يجب أن تكون درجة ORLS ≥ 90٪ للتمكين.',
    autoPilotOverride: 'يمكن لمسؤول بيت الخبرة تجاوز متطلب ORLS.',
    suggestedImprovementPoints: 'نقاط التحسين المقترحة',
    improvementArea: 'مجال التحسين',
    recommendationText: 'نص التوصية',
    priority: 'الأولوية',
    priority_High: 'عالية',
    priority_Medium: 'متوسطة',
    priority_Low: 'منخفضة',
    addRecommendation: 'إضافة توصية',
    feedbackModalTitle: 'ملاحظات للمرشح {candidateName}',
    consultantNotes: 'ملاحظات المستشار',
    sendFeedback: 'إرسال الملاحظات',
    candidateFeedbackThread: 'سلسلة ملاحظات المرشح',
    noFeedbackForStage: 'لم تتم مشاركة أي ملاحظات لهذه المرحلة بعد.',
    exportToPdf: 'تصدير إلى PDF',
    from: 'من',
    candidateReply: 'ردك',
    addYourReply: 'أضف ردك...',
    sendReply: 'إرسال الرد',
    feedbackStatus: 'الحالة',
    status_AwaitingReply: 'بانتظار الرد',
    status_Discussed: 'تمت المناقشة',
    markAsDiscussed: 'وضع علامة "تمت المناقشة"',
    initialImprovementPlan: 'خطة التحسين والتطوير الأولية',
    exportDevelopmentPdf: 'تصدير خطة التطوير (PDF)',
    coreDevelopmentAxis: 'محور أساسي',
    readinessSummary: 'ملخص الجاهزية',
    candidateReadiness: 'جاهزية المرشح',
    orgReadiness: 'الجاهزية المؤسسية',
    viewDetailsFor: 'عرض تفاصيل',
    estimatedDuration: 'المدة المقدرة',
    days: 'أيام',
    shareFeedback: 'مشاركة ملاحظات',
    startEvaluation: 'بدء التقييم',
    valuesDashboardTitle: 'لوحة تحكم القيم',
    behavioralIndicators: 'المؤشرات السلوكية',
    honesty: 'الأمانة',
    respect: 'الاحترام',
    innovation: 'الابتكار',
    collaboration: 'التعاون',
    responsibility: 'المسؤولية',
    stage_not_found: 'المرحلة غير موجودة',
    go_back: 'العودة',
    evaluationStageReadOnlyMessage: 'هذه المرحلة للتقييم. مدخلات المرشح للقراءة فقط بعد التقديم.',
    tasks: 'المهام',
    task_name: 'اسم المهمة',
    owner: 'المالك',
    duration: 'المدة',
    template: 'النموذج',
    status: 'الحالة',
    no_owner: 'غير محدد',
    no_template: 'لا يوجد',
    view_template: 'عرض',
    status_NotStarted: 'لم تبدأ',
    status_InProgress: 'قيد التنفيذ',
    status_Completed: 'مكتملة',
    status_Delayed: 'متأخرة',
    status_Cancelled: 'ملغاة',
    noTasksForStage: 'لا توجد مهام محددة لهذه المرحلة.',
    closeStage: 'إغلاق المرحلة',
    evaluationForStage: 'تقييم مرحلة: {stageName}',
    previous: 'السابق',
    next: 'التالي',
    finishEvaluation: 'إنهاء التقييم',
    surveyBuildingPhaseDescription: 'تساعدنا هذه الاستبانة على فهم تجربتك خلال مرحلة البناء والتطوير. ملاحظاتك قيمة للتحسين المستمر.',
    evaluateBuildingPhase: 'تقييم مرحلة البناء',
    planDataNotAvailable: 'بيانات الخطة غير متوفرة.',
    candidateOverview: 'نظرة عامة على المرشح',
    aiRecommendations: 'توصيات الذكاء الاصطناعي',
    noRecommendations: 'لا توجد توصيات محددة في الوقت الحالي.',
    developmentActions: 'إجراءات التطوير',
    overallProgress: 'التقدم العام',
    upcomingTasks: 'المهام القادمة',
    noUpcomingTasks: 'جميع مهام المرحلة الحالية مكتملة!',
    coachingNotes: 'ملاحظات التدريب الأخيرة',
    noCoachingNotes: 'لم تتم إضافة أي ملاحظات تدريب مؤخرًا.',
    stageClosureTitle: 'إغلاق مرحلة: {stageName}',
    stageSummary: 'ملخص المرحلة',
    stageClosure_leadershipMaturity: 'لقطة نضج القيادة',
    stageClosure_beforeStage: 'قبل المرحلة',
    lessonsLearnedPlaceholder: 'سجل أي ملاحظات أو نجاحات أو تحديات من هذه المرحلة...',
    stageClosure_signatures: 'التوقيعات',
    stageClosure_role: 'الدور',
    stageClosure_action: 'الإجراء',
    stageClosure_consultingHouseAdmin: 'مسؤول بيت الخبرة',
    stageClosure_organizationAdmin: 'مسؤول المؤسسة',
    stageClosure_signedOn: 'تم التوقيع في',
    stageClosure_signaturePending: 'التوقيع معلق',
    stageClosure_signNow: 'التوقيع الآن',
    stageClosure_signatureNotAllowed: 'غير مسموح',
    confirmClosure: 'أؤكد أن جميع المعلومات دقيقة وأن المرحلة جاهزة للإغلاق.',
    stageClosure_exportSummary: 'تصدير الملخص',
    confirmAndCloseStage: 'تأكيد وإغلاق المرحلة',
    settings: 'الإعدادات',
    changeLanguage: 'تغيير اللغة',
    viewValuesDashboard: 'لوحة القيم',
    organizationalOverview: 'نظرة عامة على المؤسسات',
    highCriAlert: 'تم اكتشاف مؤشر مقاومة تغيير مرتفع.',
    avgReadiness: 'متوسط الجاهزية',
    topValues: 'أبرز القيم',
    monthlyReports: 'التقارير الشهرية المعلقة',
    viewReport: 'عرض التقرير',
    markReviewed: 'وضع علامة "تمت المراجعة"',
    noPendingReports: 'لا توجد تقارير معلقة للمراجعة.',
    globalTopImprovementThemes: 'أبرز محاور التحسين الشاملة',
    reportDetails: 'تفاصيل التقرير',
    downloadPdf: 'تحميل PDF',
    close: 'إغلاق',
    analysisComplete: 'اكتمل التحليل اليومي!',
    analyzing: 'جاري التحليل...',
    runDailyAnalysis: 'تشغيل التحليل اليومي',
    liveJourneyDashboard: 'لوحة التحكم المباشرة للرحلة',
    backToJourney: 'العودة للرحلة',
    journeyCompletedMessage: 'اكتملت الرحلة!',
    timelineSummary: 'ملخص الجدول الزمني',
    keyInsights: 'الرؤى الرئيسية من الرحلة',
    noJourneyInsights: 'لم يتم تسجيل رؤى محددة لهذا المرشح خلال الرحلة.',
    exportSummary: 'تصدير الملخص',
    setupReadinessTitle: 'لنقم بإعداد تجربتك',
    setupReadinessSubtitle: 'بعض الأسئلة لتخصيص النظام لاحتياجاتك.',
    userTypeLeader: 'مرشح قيادي',
    userTypeHR: 'مدير موارد بشرية / مدير مشروع',
    userTypeInstitution: 'صانع قرار في المؤسسة',
    userTypeConsultant: 'مستشار',
    readinessQuestion1: 'ما مدى إلمامك بمفاهيم تخطيط التعاقب الوظيفي؟',
    readinessAnswerLow: 'مبتدئ',
    readinessAnswerMedium: 'متوسط',
    readinessAnswerHigh: 'خبير',
    readinessQuestion2: 'هل لدى مؤسستك خطة تعاقب وظيفي حالية؟',
    readinessAnswerNo: 'لا، نحن نبدأ من الصفر',
    readinessAnswerInProgress: 'هي قيد التطوير',
    readinessAnswerYes: 'نعم، لدينا خطة رسمية',
    submitAndContinue: 'إرسال ومتابعة',
    surveySubmittedTitle: 'تم إرسال الاستبيان',
    surveySubmittedSubtitle: 'شكراً لملاحظاتك القيمة!',
    monthlyReportGenerated: 'تم إنشاء تقرير شهري جديد لـ {orgName}.',
    stageClosedTitle: 'تم إغلاق المرحلة',
    stageClosedSubtitle: 'تم إغلاق المرحلة الفردية \'{stageName}\'. تم حفظ ملاحظاتك.',
    pendingRequirementsTitle: 'المتطلبات المعلقة',
    validation_tasksNotCompleted: 'يجب إكمال 90% على الأقل من مهام المرحلة.',
    validation_lessonsLearnedMissing: 'يجب تعبئة حقل الدروس المستفادة.',
    validation_finalRatingMissing: 'يجب تقديم تقييم نهائي لتجربة المرحلة.',
    validation_processRatingsMissing: 'يجب تقييم جميع عناصر مراجعة العملية.',
    toast_readyForReview_title: 'جاهز للمراجعة',
    toast_readyForReview_subtitle: 'تم توقيع إغلاق مرحلة {candidateName} بالكامل وهو الآن جاهز للمراجعة النهائية والأرشفة.',
    validation_minReadyCandidatesNotMet: 'يجب أن يكون لدى 80% على الأقل من المرشحين درجة جاهزية تبلغ 85% أو أعلى.',
    validation_pendingReviews: 'يجب الموافقة على جميع الخطط الأخرى التي تنتظر المراجعة أو أرشفتها قبل المتابعة.',
    stageClosureDashboardTitle: 'لوحة المراجعة المؤسسية',
    closureStatus: 'الحالة',
    approveCandidateClosure: 'اعتماد الإغلاق',
    returnCandidateForFix: 'إعادة للمراجعة',
    toast_approve_success_title: 'تم اعتماد الإغلاق',
    toast_approve_success_subtitle: 'تم اعتماد إغلاق المرشح {candidateName} بنجاح.',
    toast_return_success_title: 'تم إرجاع الإغلاق',
    toast_return_success_subtitle: 'تم إرجاع إغلاق المرشح {candidateName} لمزيد من المراجعة.',
    toast_stage_closure_approved_title: 'اعتماد إغلاق المرحلة',
    toast_stage_closure_approved_subtitle: "تم اعتماد إغلاق مرحلة '{stageName}' وأرشفتها.",
    toast_stage_closure_approved_candidate_subtitle: "تم اعتماد مرحلتك '{stageName}'! رحلتك مستمرة.",
    insight_stage_archived: "تم إغلاق وأرشفة المرحلة المؤسسية '{stageName}' للمرشح {candidateName} رسميًا.",
    status_pending: 'معلق',
    status_readyForReview: 'جاهز للمراجعة',
    status_archived: 'مؤرشفة',
    toast_closure_returned_title: 'تم إرجاع الإغلاق',
    toast_closure_returned_subtitle: 'تم إرجاع إغلاق {candidateName} للمراجعة. تم إعادة تعيين التوقيعات.',
    stageClosure_pendingFinalApproval: 'إغلاق هذه المرحلة الآن في انتظار الموافقة النهائية في لوحة المراجعة المؤسسية.',
    stageClosure_archivedMessage: 'تم إغلاق هذه المرحلة وأرشفة جميع البيانات المرتبطة بها بشكل دائم.',
    overallJourneyProgress: 'التقدم العام للرحلة',
    tooltip_lri: 'مؤشر جاهزية القيادة (LRI): يقيس جاهزية المرشح بناءً على الكفاءة، السلوك، توافق القيم، ومرونة التعلم.',
    tooltip_maturity: 'مؤشر النضج القيادي: يقيس النسبة المئوية للمهام المكتملة في رحلة التطوير.',
    tooltip_bvi: 'مؤشر سرعة السلوك (BVI): يتتبع زخم التطور السلوكي بناءً على إكمال المهام والتأملات.',
    tooltip_lqm: 'زخم جودة القيادة (LQM): يعكس جودة ومشاعر تفاعل المرشح وتأملاته.',
    executiveSummary: 'ملخص تنفيذي',
    remainingTasks: 'المهام المتبقية',
    completionTimeline: 'الخط الزمني للإنجاز',
    stage_summary_STG1: 'تركز هذه المرحلة الأولية على التقييم الأساسي والتخطيط الاستراتيجي لمواءمة المرشح مع احتياجات القيادة المستقبلية للمؤسسة.',
    stage_summary_STG2: 'مرحلة التطوير الأساسية حيث يشارك المرشح بنشاط في برامج التأهيل والإرشاد والتطبيق العملي لبناء الكفاءات القيادية الرئيسية.',
    stage_summary_STG3: 'مرحلة تركز على التقييم حيث يطبق المرشح المهارات المكتسبة في سيناريوهات واقعية، ويتم تقييم أدائه وفعالية التدريب.',
    stage_summary_STG4: 'تضمن المرحلة النهائية انتقالًا سلسًا ونجاحًا على المدى الطويل من خلال التركيز على المتابعة بعد الانتقال ورصد الأثر والتحسين المستمر.',
    kpi: 'مؤشر الأداء الرئيسي',
    finalReadinessDelta: 'صافي تغير الجاهزية',
    kpiDescription: "التغير في درجة LRI للمرشح خلال هذه المرحلة.",
    targetVsActual: 'المقارنة مع الأهداف',
    plannedDuration: 'المدة المخططة',
    actualDuration: 'المدة الفعلية',
    plannedDurationDescription: 'الوقت المقدر لهذه المرحلة بناءً على مقاييس الجاهزية.',
    actualDurationDescription: 'الوقت المحاكى المستغرق لإكمال جميع مهام هذه المرحلة.',
    recommendationsForNextStage: 'توصيات للمرحلة التالية',
    generateRecommendations: 'توليد التوصيات',
    generatingRecommendations: 'جاري التوليد...',
    comprehensiveDashboard: 'لوحة التحكم الشاملة',
    manageOrganizations: 'إدارة المؤسسات',
    candidates: 'المرشحون',
    manageCandidates: 'إدارة المرشحين',
    total: 'الإجمالي',
    active: 'النشطون',
    completed: 'المكتملون',
    template_standard_name: 'مسار القيادة القياسي',
    template_standard_desc: 'خطة متوازنة للقادة الناشئين في الشركات.',
    template_exec_name: 'المسار التنفيذي السريع',
    template_exec_desc: 'خطة معجلة للمديرين التنفيذيين ذوي الإمكانات العالية.',
    template_gov_name: 'قيادة القطاع العام',
    template_gov_desc: 'تطوير شامل للأدوار الحكومية.',

    // New keys for localization
    unitActivities: 'أنشطة الوحدة',
    learningMaterialChangeMgmt: 'مادة علمية: قيادة التغيير',
    stakeholderMapActivity: 'نشاط تطبيقي: خريطة أصحاب المصلحة',
    professionalReflection: 'انعكاس مهني',
    shortAssessment: 'تقييم قصير',
    uploadDeliverables: 'رفع المخرجات',
    buildingPhaseIntro: 'تمهيد عن مرحلة البناء',
    contentPlaceholder: 'منطقة عرض المادة (Placeholder)',
    generateMcq: '✨ توليد أسئلة اختيار من متعدد',
    generatingMcqs: 'جاري توليد الأسئلة...',
    checkAnswer: 'تحقق من الإجابة',
    correctAnswer: 'إجابة صحيحة!',
    incorrectAnswer: 'إجابة خاطئة، حاول مرة أخرى.',
    stakeholderMapTaskDesc: 'نفّذ النشاط التالي: ارسم خريطة لأصحاب المصلحة في مشروعك القيادي.',
    submitTask: 'إرسال المهمة',
    writeYourReflection: 'اكتب انعكاسك حول ما تعلمته في هذه المرحلة:',
    myThoughtsPlaceholder: 'أفكاري حول هذه التجربة...',
    uploadDeliverable: 'رفع المخرج',
    quickAssessment: 'تقييم سريع:',
    questionNum: 'سؤال {num}',
    buildingPhaseIntroTitle: 'مقدمة عن مرحلة البناء والتطوير',
    buildingPhaseIntroDesc: 'في هذه المرحلة، ستركز على تطوير الكفاءات القيادية الأساسية من خلال مجموعة من الأنشطة التفاعلية والمهام التطبيقية. استعد لرحلة تعلم مكثفة ستساهم في صقل مهاراتك وتجهيزك للمسؤوليات القادمة.',
    activityInteraction: 'التفاعل على هذا النشاط',
    writeYourNotesPlaceholder: 'أكتب ملاحظاتك...',
    commentingAs: 'أُعلّق بصفتي...',
    role_candidate_short: 'مرشح',
    role_consultant_short: 'مستشار',
    role_org_admin_short: 'مسؤول مؤسسة',
    rateActivityUsefulness: 'قيّم فائدة هذا النشاط:',
    createNewPlanNewFlow: 'إنشاء خطة (التدفق الجديد)',
    noSuccessionPlansFound: 'لم يتم العثور على خطط تعاقب لهذا العرض.',
    clickToGetStarted: 'انقر على "{createNewPlan}" للبدء.',
    quickCandidateSwitch: 'التبديل السريع للمرشح',
    valuesDashboard: 'لوحة القيم',
    alert_fillAllFields: 'يرجى ملء جميع الحقول',
    toBeDefined: 'سيتم تحديدها لاحقاً',
    generatedPlanWillAppearHere: 'ستظهر خطتك التي تم إنشاؤها هنا.',
    alert_settingsClicked: 'تم النقر على الإعدادات',
    alert_noDemoUserForRole: 'لم يتم العثور على مستخدم تجريبي لهذا الدور.',
    confirm_deleteCandidate: 'هل أنت متأكد من رغبتك في حذف هذا المرشح؟',
    toast_planCreated_title: 'تم إنشاء الخطة',
    toast_planCreated_subtitle: 'تم إنشاء خطة جديدة بنجاح لـ {candidateName}.',
    loadingConsultantDashboard: 'جاري تحميل لوحة التحكم الشاملة...',
    loadingStageData: 'جاري تحميل بيانات المرحلة...',
    backToList: 'العودة إلى القائمة',
    editOrg: 'تعديل: {name}',
    addNewOrg: 'إضافة مؤسسة جديدة',
    orgName: 'اسم المؤسسة',
    inactive: 'غير نشطة',
    description: 'الوصف',
    logoUrl: 'رابط الشعار',
    contactInfo: 'معلومات الاتصال',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    address: 'العنوان',
    alert_orgNameRequired: 'اسم المؤسسة مطلوب.',
    creationDate: 'تاريخ الإنشاء',
    candidateCount: 'عدد المرشحين',
    noOrgsFound: 'لم يتم العثور على مؤسسات.',
    clickAddNewOrg: 'اضغط على "إضافة مؤسسة جديدة" للبدء.',
    edit: 'تعديل',
    generalInfo: 'معلومات عامة',
    noDescription: 'لا يوجد وصف.',
    statistics: 'إحصائيات',
    activeCandidate: 'مرشح نشط',
    candidateList: 'قائمة المرشحين',
    noCandidatesForOrg: 'لا يوجد مرشحون لهذه المؤسسة.',
    addCandidate: 'إضافة مرشح',
    searchByNameOrPosition: 'بحث بالاسم أو المنصب...',
    filterByStatus: 'فلتر بالحالة',
    filterByDepartment: 'فلتر بالقسم',
    clearFilters: 'مسح الفلاتر',
    candidateName: 'اسم المرشح',
    completionPercentage: 'نسبة الإنجاز',
    monitorJourney: 'متابعة الرحلة',
    delete: 'حذف',
    alert_nameAndTargetRequired: 'الاسم والمنصب المستهدف حقول مطلوبة.',
    editCandidateData: 'تعديل بيانات المرشح',
    addNewCandidate: 'إضافة مرشح جديد',
    fullName: 'الاسم الكامل',
    currentPosition: 'المنصب الحالي',
    department: 'القسم',
    profilePictureUrl: 'رابط الصورة الشخصية',
    save: 'حفظ',
    paused: 'متوقف مؤقتاً',
    archived: 'مؤرشف',
    lastActivity: 'آخر نشاط',
    // StageDetailScreen keys
    viewStageDashboard: 'عرض لوحة تحكم المرحلة',
    advancedStageManagement: 'إدارة المرحلة المتقدمة',
    step: 'الخطوة',
    goal: 'الهدف',
    alert: 'تنبيه',
    category: 'الفئة',
    targetDate: 'التاريخ المستهدف',
    sendAlert: 'إرسال',
    evaluateStageExperience: 'تقييم التجربة لهذه المرحلة',
    addAdvancedStepTitle: 'إضافة خطوة جديدة لإدارة المرحلة المتقدمة',
    addAdvancedStep: 'إضافة خطوة',
    stepCategory: 'فئة الخطوة',
    targetCompletionDate: 'التاريخ المستهدف لإنجاز الخطوة',
    advancedStepStatus_NotStarted: 'لم تبدأ',
    advancedStepStatus_InProgress: 'جارية',
    advancedStepStatus_Completed: 'مكتملة',
    stepCategory_operational: 'إجرائية',
    stepCategory_developmental: 'تطويرية',
    stepCategory_followup: 'متابعة',
    raci_org_admin: 'مسؤول المؤسسة',
    raci_project_manager: 'مدير المشروع',
    raci_consultant: 'المستشار',
    raci_candidate: 'المرشح',
    raci_none: '-',
    alertSentTitle: 'تم إرسال التنبيه',
    alertSentSubtitle: 'تم إرسال تنبيه بالخطوة المتقدمة: {stepName}',
    unauthorized: 'غير مصرح به',
    unauthorized_add_step: 'ليس لديك صلاحية لإضافة خطوات تشغيلية.',
    incomplete_data: 'بيانات غير مكتملة',
    incomplete_data_add_step: 'يرجى ملء حقلي الخطوة والهدف.',
    error_add_step: 'تعذر حفظ الخطوة، يرجى المحاولة لاحقًا.',
  }
};